[tool.poetry]
name = "time_series"
version = "0.1.0"
description = "Awesome time series tools!"
authors = ["Emiel Deprost", "Jeroen Van Der Donckt", "Jonas Van Der Donckt"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.2.3"
numpy = "^1.20.1"
pathos = "^0.2.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pydocstyle = "^5.1.1"
Sphinx = "^3.5.2"
jupyterlab = "^3.0.12"
memory-profiler = "^0.58.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
